name: coin_pulse
description: CoinPulse Your gateway to a colorful financial future

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7
  animate_do: ^3.1.2
  text_transformation_animation: ^0.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/coin_pulse_app_icon.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
